# NumPy

In [36]:
import numpy as np

In [37]:
#criando vetores a partir de uma lista ou tupla

lista = [1, 2, 3, 4]
tupla = (1, 2, 3, 4)

array_a_partir_de_lista = np.array(lista)
array_a_partir_de_tupla = np.array(tupla)

array_a_partir_de_lista




array([1, 2, 3, 4])

In [38]:
#usando um range
array_simples = np.arange(10)
array_sequencial = np.arange(10, 100, 10)
#np.arange(inicio, fim, frequencia)

array_simples, array_sequencial

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [39]:
#criando arrays de zeros ou ums

vetor_zero = np.zeros(5)
vetor_um = np.ones(5)

vetor_zero, vetor_um

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [40]:
#criando vetores aleatórios

vetor_aleatorio_entre_0_1 = np.random.rand(3, 2)
#vetor_aleatorio_entre_0_1 = np.random.rand(QUANT_VETORES, TAMANHO)
print(vetor_aleatorio_entre_0_1)

vetor_aleatorio_inteiro = np.random.randint(low = 3, high=7, size=3, )
print(vetor_aleatorio_inteiro)

vetor_aleatorio_com_negativos = np.random.uniform(low = -3, high=7, size=3)
print(vetor_aleatorio_com_negativos)


[[0.67151465 0.81617294]
 [0.91012378 0.90598101]
 [0.26200885 0.6662051 ]]
[6 6 3]
[4.15307184 4.65103345 1.73916698]


In [41]:
#criando arrays bi ou tridimensionais

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [7, 8, 9]

array2d = np.array([lista1, lista2])
array3d = np.array([lista1, lista2, lista3])

array2d, array3d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [42]:
#criando matrizes
matriz = np.matrix([[20, 30], [90, 80]])

matriz

matrix([[20, 30],
        [90, 80]])

In [43]:
#lista x numpy array

lista_1 = [1, 1, 1, 1]
lista_2 = [2, 2, 2, 2]

print(lista_1 + lista_2)

print(np.array(lista_1) + np.array(lista_2))

[1, 1, 1, 1, 2, 2, 2, 2]
[3 3 3 3]


In [59]:
#teste lista x array numpy

range_test = 1000
X = range(range_test)
Y = range(range_test)
#logica propria
lista_test = [numero + Y[index] for numero, index in enumerate(X)]
#logica aula
lista_test = [X[i] + Y[i] for i in range(len(X))]


import timeit

tempo_proprio = timeit.timeit('''X = range(100000); Y = range(100000); [numero + Y[index] for numero, index in enumerate(X)] ''', number=100)
tempo_aula = timeit.timeit('''X = range(100000); Y = range(100000); [X[i] + Y[i] for i in range(len(X))] ''', number=100)
tempo_array = timeit.timeit('''X = np.arange(100000); Y = np.arange(100000); X + Y ''',
number=100,
setup="import numpy as np")

print(tempo_proprio)
print(tempo_aula)
print(tempo_array)

print(f'Os vetores são {tempo_aula/tempo_array} vezes mais rápidos')





2.4227977999980794
2.701516900007846
0.02621009999711532
Os vetores são 103.07159836494993 vezes mais rápidos


# Desafios

In [64]:
print('Bem vindo, digite 3 cotações!')
cotacoes_lista = []
try:
    for i in range(3):
        cotacoes_lista.append(float(input('Digite a cotação: ')))
except Exception as erro:
    print('Ocorreu um erro:', erro)
else:
    cotacoes_array = np.array(cotacoes_lista)

print(cotacoes_array)


Bem vindo, digite 3 cotações!
Ocorreu um erro: could not convert string to float: 'awd'
[15. 12. 13.]


In [66]:

array_sequencial = np.arange(int(input('Digite o valor minimo')), int(input('Digite o valor máximo')))
print(array_sequencial)

In [83]:
lista_numeros = []
lista_numeros.append(np.random.randint(low = 0, high=60, size= 1)[0])

while len(lista_numeros) < 6:
    numero_aleatorio = np.random.randint(low = 0, high=60, size= 1)[0]

    if numero_aleatorio not in lista_numeros:
        lista_numeros.append(numero_aleatorio)
    
print(lista_numeros)
print(f'A chance de ganhar é de:', np.random.rand(1)[0])

[56, 28, 29, 19, 40, 8]
A chance de ganhar é de: 0.29398218772522855
