# NumPy

In [2]:
import numpy as np

In [3]:
#juntar dois arrays

array1 = np.arange(20, 25)
array2 = np.arange(15)

array_completo = np.concatenate([array1, array2])

array_completo

array([20, 21, 22, 23, 24,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In [6]:
#separando em dois arrays
# np.split(array_completo, [5]) ~> retorna dois arrays
array_separado1, array_separado2 = np.split(array_completo, [5])

print(array_separado1, array_separado2)

[20 21 22 23 24] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
#colocando novos dados em array

array_completo = np.append(array_completo, 2000) #adiciona ao final
array_completo = np.insert(array_completo, 5, 11) #insere na pos
print(array_completo)

# comparando com listas
# lista.append(elem)
# array = np.append(array, elem)

[  20   21   22   23   24   11   11    0    1    2    3    4    5    6
    7    8    9   10   11   12   13   14 2000 2000 2000]


In [12]:
#deletando dados de um array
print(array_completo)
array_completo = np.delete(array_completo, -1) #deletando o ultimo elemento
print(array_completo)

[  20   21   22   23   24   11   11    0    1    2    3    4    5    6
    7    8    9   10   11   12   13   14 2000]
[20 21 22 23 24 11 11  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
#reshape
array_3x3 = np.arange(9).reshape(3, 3) #metodo util para fazer regressao linear
array_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#trocando números dentro de uma condição
array_inicial = np.array([4, 4, 4, 4, 7, 6, 5, 32, 2, 45, 4, 34, 10, 52])

#trocando todos os num menores que 40 por 0
print(array_inicial<40) #[ True  True  True  True  True  True  True  True  True False  True  True True False]

array_inicial[array_inicial < 40] = 0
#define o valor declarado para cada elemento verdadeiro dentro da condição

array_inicial

[ True  True  True  True  True  True  True  True  True False  True  True
  True False]


array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 45,  0,  0,  0, 52])

In [19]:
#ordenando objetos dentro da lista

array_desordenado = np.array([4, 4, 4, 4, 7, 6, 5, 32, 2, 45, 4, 34, 10, 52])
array_crescente = np.sort(array_desordenado)
array_decrescente = -np.sort(-array_desordenado)

print(array_crescente)
print(array_decrescente)

[ 2  4  4  4  4  4  5  6  7 10 32 34 45 52]
[52 45 34 32 10  7  6  5  4  4  4  4  4  2]


### Desafios

In [36]:

try:
    lucros_empresas = np.array([])
    lucros_empresas = np.append(lucros_empresas, int(input('Digite o lucro da Vale: ')))
    lucros_empresas = np.append(lucros_empresas, int(input('Digite o lucro da Petro: ')))
    lucros_empresas = np.append(lucros_empresas, int(input('Digite o lucro da Weg: ')))
except ValueError:
    print('Lucro inserido deve ser um número inteiro')

else:
    lucros_ordem_crescente = np.sort(lucros_empresas)
    print('Lucros em ordem crescente:', lucros_ordem_crescente)
    lucros_ordem_decrescente = -np.sort(-lucros_empresas)
    print('Lucros em ordem decrescente:', lucros_ordem_decrescente)

Lucros em ordem crescente: [30. 50. 90.]
Lucros em ordem decrescente: [90. 50. 30.]


In [38]:
#Gabarito aula
empresas = np.array(["Weg", "Vale", "Petro"])
array_lucros = np.array([])

for empresa in empresas:
    lucro = float(input(f'Digite o lucro da empresa {empresa}'))
    array_lucros = np.append(array_lucros, lucro)

array_lucros = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior pro menor: {array_lucros}')

Lucro das empresas, do maior pro menor: [19. 16. 10.]
